doctrine:
    dbal:
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        default_connection: default

        connections:
            default:
                driver: 'pdo_pgsql'
                url: "%env(resolve:DATABASE_URL_API)%"
                profiling_collect_backtrace: "%kernel.debug%"
                use_savepoints: true
                server_version: "%env(resolve:POSTGRES_VERSION)%"

            pool:
                driver: 'pdo_pgsql'
                url: "%env(resolve:DATABASE_URL_POOL)%"
                profiling_collect_backtrace: "%kernel.debug%"
                use_savepoints: true
                server_version: "%env(resolve:POSTGRES_VERSION)%"
    orm:
        default_entity_manager: default
        enable_lazy_ghost_objects: true

        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Dataviz:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Domain/Dataviz"
                        prefix: 'App\Domain\Dataviz'
                        alias: Dataviz

            pool:
                connection: pool
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Datapool:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Domain/Datapool"
                        prefix: 'App\Domain\Datapool'
                        alias: Datapool

        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            default_connection: default

            connections:
                default:
                    dbname_suffix: "_test%env(default::TEST_TOKEN)%"
                    url: "%env(resolve:DATABASE_URL_API)%"
                    profiling_collect_backtrace: "%kernel.debug%"

                pool:
                    dbname_suffix: "_test%env(default::TEST_TOKEN)%"
                    url: "%env(resolve:DATABASE_URL_POOL)%"
                    profiling_collect_backtrace: "%kernel.debug%"

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
