when@dev: &dev # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        orm:
            reset:
                connections:

                    # Default:
                    - default
                    - pool

                # Entity Managers to reset with ResetDatabase trait
                entity_managers:

                    # Default:
                    - default
                    - pool

                mode: migrate

when@test: *dev
