tile_buffer = 64

[webserver]
port = ":${TEGOLA_PORT}"

[cache]
type = "file"
basepath = "/tmp/tegola"

[[providers]]
name = "datapool"
type = "postgis"
uri = "postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:5432/${POSTGRES_DBNAME}?sslmode=${SSL_MODE}"
srid = 4326
max_connections = 50

  [[providers.layers]]
  name = "municipality"
  id_fieldname = "gid"
  tablename = "territoire.municipality"
  geometry_type = "MultiPolygon"
  sql = """
    SELECT gid, insee_com as codgeo, nom as label, 
      CASE
        WHEN !ZOOM! <= 6 THEN ST_AsBinary(ST_SimplifyPreserveTopology(geom, 0.05))
        WHEN !ZOOM! <= 8 THEN ST_AsBinary(ST_SimplifyPreserveTopology(geom, 0.01))
        ELSE ST_AsBinary(geom)
      END AS geom
    FROM territoire.municipality
    WHERE ST_Intersects(geom, !BBOX!)
  """

[[maps]]
name = "municipality"
tile_buffer = 0
center = [2.5, 46.5, 6.0]

  [[maps.layers]]
  provider_layer = "datapool.municipality"
  min_zoom = 0
  max_zoom = 10
