api_platform:
    title: Backoffice dataviz
    version: 1.0.0
    show_webby: false

    openapi:
        contact:
            name: Maxime PREUILH
            email: maxime.preuilh@gmail.com

    path_segment_name_generator: 'App\ApiResource\SingularPathSegmentNameGenerator'

    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    mapping:
        paths:
            - "%kernel.project_dir%/src/Entity/"
    patch_formats:
        json: ["application/merge-patch+json"]

    # The list of enabled formats. The first one will be the default.
    formats:
        jsonld:
            mime_types: ["application/ld+json"]
        json:
            mime_types: ["application/json"]
        multipart:
            mime_types: ["multipart/form-data"]
        html:
            mime_types: ["text/html"]

    error_formats:
        jsonproblem: ["application/problem+json"]
        jsonld: ["application/ld+json"]
        jsonapi: ["application/vnd.api+json"]

    docs_formats:
        jsonld: ["application/ld+json"]
        jsonopenapi: ["application/vnd.openapi+json"]
        html: ["text/html"]

    # change this to true if you use controllers
    use_symfony_listeners: false

    collection:
        # The name of the query parameter to filter nullable results (with the ExistsFilter).
        exists_parameter_name: "exists"

        # The default order of results.
        order: "ASC"

        # The name of the query parameter to order results (with the OrderFilter).
        order_parameter_name: "order"

        pagination:
            # The default name of the parameter handling the page number.
            page_parameter_name: "page"

            # The name of the query parameter to enable or disable pagination.
            enabled_parameter_name: "pagination"

            # The name of the query parameter to set the number of items per page.
            items_per_page_parameter_name: "itemsPerPage"

            # The name of the query parameter to enable or disable the partial pagination.
            partial_parameter_name: "partial"

    defaults:
        stateless: true

        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]

        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true

        # To enable or disable pagination for all resource collections.
        pagination_enabled: true

        # To allow the client to enable or disable the pagination.
        pagination_client_enabled: false

        # To allow the client to set the number of items per page.
        pagination_client_items_per_page: true

        # To allow the client to enable or disable the partial pagination.
        pagination_client_partial: false

        # The default number of items per page.
        pagination_items_per_page: 50

        # The maximum number of items per page.
        pagination_maximum_items_per_page: 200
