vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        provider_image:
            uri_prefix: /media/provider
            upload_destination: '/var/shared_data/provider'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
